pipelines:
  - name: docker
    steps:
      - name: docker
        type: Bash
        configuration:
          integrations:
            - name: yardeng_hts1_artifactory
        execution:
          onStart:
            - docker images
            - docker login hts1.jfrog.io --username yardeng --password $int_yardeng_hts1_artifactory_apikey
            - docker pull hts1.jfrog.io/artifactory/ohadl-docker-test/hello-world
            - docker images
            - docker save hts1.jfrog.io/artifactory/ohadl-docker-test/hello-world .
            - ls -lah
