pipelines:
  - name: docker
    steps:
      - name: docker
        type: Bash
        configuration:
          integrations:
            - name: ArtifactoryIntegration
        execution:
          onStart:
            - docker images
            - docker login --username $int_ArtifactoryIntegration_user --password $int_ArtifactoryIntegration_apikey $int_ArtifactoryIntegration_url
            - docker pull gittalabs.jfrog.io/docker/busybox
            - docker images
            - docker save gittalabs.jfrog.io/docker/busybox -o busybox.tar.gz
            - ls -lah
