pipelines:
  - name: docker
    steps:
      - name: docker
        type: Bash
        configuration:
          integrations:
            - name: GittaLabs
        execution:
          onStart:
            - docker images
            - docker login --username $int_GittaLabs_user --password $int_GittaLabs_apikey $int_GittaLabs_url
            - docker pull gittalabs.jfrog.io/docker/busybox
            - docker images
            - docker save gittalabs.jfrog.io/docker/busybox .
            - ls -lah
