pipelines:
  - name: docker
    steps:
      - name: docker
        type: Bash
        configuration:
          integrations:
            - name: yardeng_hts1_artifactory
        execution:
          onStart:
            - docker images
            - docker login --username yardeng --password $int_yardeng_hts1_artifactory_apikey hts1-ohadl-docker-test.jfrog.io
            - docker pull hts1.jfrog.io/artifactory/ohadl-docker-test/hello-world
            - docker images
            - docker save hts1.jfrog.io/artifactory/ohadl-docker-test/hello-world .
            - ls -lah
